name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  ELIXIR_VERISON: 1.16.2
  OTP_VERSION: 26

jobs:
  build_test:
    name: Build Stage (TEST)
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERISON }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERISON }}-${{ env.MIX_ENV }}-${{ hashFiles('mix.lock') }}

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile --skip-umbrella-children

  build_dev:
    name: Build Stage (DEV)
    runs-on: ubuntu-latest
    env:
      MIX_ENV: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERISON }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERISON }}-${{ env.MIX_ENV }}-${{ hashFiles('mix.lock') }}

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile --skip-umbrella-children

  linter:
    name: Linter Stage
    needs: [build_test, build_dev]
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERISON }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERISON }}-${{ env.MIX_ENV }}-${{ hashFiles('mix.lock') }}

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

  tests:
    name: Tests Stage
    needs: [build_test, build_dev]
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERISON }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERISON }}-${{ env.MIX_ENV }}-${{ hashFiles('mix.lock') }}

      - name: Run Unit Tests
        run: |
          mix coveralls.github --umbrella
        env:
          GITHUB_TOKEN: ${{ github.token }}

  deploy:
    name: Deploy Stage
    needs: [linter, tests]
    runs-on: ubuntu-latest
    env:
      MIX_ENV: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERISON }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERISON }}-${{ env.MIX_ENV }}-${{ hashFiles('mix.lock') }}

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile --skip-umbrella-children

      - name: Deploy to Hex
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
